esphome:
  name: doorbell
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  log_topic: "doorbell/logs"
  discovery: true

binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    name: "doorbell"
    filters:
    - delayed_on: 20ms
    - delayed_off: 20ms

logger:
  esp8266_store_log_strings_in_flash: false

ota:
